# config/packages/liip_imagine.yaml

liip_imagine:
    driver: "gd"
    filter_sets:
        thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
